[package]
name = "exc03"
version = "0.1.0"
authors = ["grzes5003 <grzes.kulinski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
rand_distr = "0.4.0"
